#!/usr/bin/env ruby

lib = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
# $LOAD_PATH << File.join(__dir__, "../lib")
require "rbs"
require "rbs/cli"

RBS::CLI.new(stdout: STDOUT, stderr: STDERR).run(ARGV.dup)
